# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit Simple Linear Regression
#'
#' This function takes the input data, assuming a column of ones in the X
#' matrix to estimate the intercept, and returns as a list the estimates,
#' standard errors, confidence intervals, residuals, and predicted values.
#'
#' @param X an arma::max that contains the users input data and a column of ones
#' @param Y and arma::vec that contains the users input data
#' @returns a list containing the estimates of B0 B1, their standard errors
#' confidence intervals, residuals, and predicted values. This list is sent back
#' to the R Wrapper function fitModel.
#' @export
NULL

fitLin <- function(X, Y) {
    .Call(`_SimpLin_fitLin`, X, Y)
}

